name = "raindrop-proxy"
main = "src/index.js"
compatibility_date = "2025-11-17"
workers_dev = true

# 如需绑定到你自己的域名，请在这里填写 account_id / zone_id / routes
# account_id = "your_account_id"
# zone_id = "your_zone_id"
# [[routes]]
# pattern = "suus.me/api/*"
# zone_id = "your_zone_id"
